---
info:
  scm-url: "@scm.url@"
  build-url: "http://travis-ci.org/@env.TRAVIS_REPO_SLUG@/builds/@env.TRAVIS_BUILD_ID@"
  stage: test

logging:
  file: "target/boot-admin-sample.log"

management:
  context-path: "/actuator"

spring:
  application:
    name: "@pom.artifactId@"
  boot:
    admin:
      url: http://localhost:8080
  profiles:
    active:
      - secure

---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

---
spring:
  profiles: secure
  boot:
    admin:
      notify:
        mail:
          to: adobe1874@126.com
          from: 335747019@qq.com
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    properties:
      smtpAuth: true
      smtpStarttlsEnable: true
      smtpSslTrust: smtp.qq.com
    username: 335747019@qq.com
  # 此处为授权码
    password: yatkaaaonamfbjih

security:
  user:
    name: user
    password: pass

  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
      filter-order: 3
    client:
      clientId: service
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: server-a

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

dingding:
  enabled: true
  # 需要 @ 开发人员的状态
  need-at-state: DOWN,OFFLINE
  mobiles:
    - "17682310302"
  ignore-changes: #empty, nothing to ignore
  webhook-url: https://oapi.dingtalk.com/robot/send?access_token=811ccb2a35520a3e0b83040f215005f0a584103b99833e2727b9c6d534d610a7
  username: wozaijia admin
  message: "*#{application.name}* (#{application.id}) is *#{to.status}*"