spring:
  application:
    name: server-b

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
      filter-order: 3
    client:
      clientId: service
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: server-a

  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
