server:
  port: 7777

spring:
  application:
    name: server-a

management:
  security:
    enabled: false

security:
  user:
    name: user
    password: pass

  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
      filter-order: 3
    client:
      clientId: service
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}